### ISSUE TITLE
Add GitLab CI build instructions

### ISSUE THREAD

**Issue by ronaldtse** [paneron/extension-aperis-site#2]
IEEE SA Open needs to run the Aperis editor on their GitLab platform, we should allow that.

**Comment by strogonoff** [comment]
Closed mistakenly. In 1.0.0-alpha22, configurable deployment setup is supported. What remains to be done is adding GitLab Pages/GitHub pages deployment setup configurations [here](https://github.com/paneron/extension-aperis-site/tree/master/src/deployment).

**Comment by strogonoff** [comment]
<img width="351" alt="Screenshot 2020-11-10 at 6 02 16 PM" src="https://user-images.githubusercontent.com/292959/98652370-72b99000-2333-11eb-9d61-88349387a7fc.png">

**Comment by strogonoff** [comment]
As of Aperis Paneron extension v1 alpha 26, the following GitLab Pages deployment configuration added:

```
image: "node:14"
pages:
  cache:
    paths: [node_modules]
  artifacts:
    paths: [dist]
  only: [master]
  script:
    - yarn install
    - yarn build
```

Testing pending.
